services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: binance_mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "Fintech2026!Sql"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
